pub const ALLOVR_AOVR_STAKE_POOL_REGISTRY_PREFIX: &str = "ALLOVR_AOVR_STAKE_POOL_REGISTRY";
pub const ALLOVR_AOVR_STAKE_POOL_PREFIX: &str = "ALLOVR_AOVR_STAKE_POOL";

pub const ALLOVR_AOVR_STAKE_NUM_POOLS: usize = 100;
pub const ALLOVR_AOVR_STAKE_NUM_STAKES_IN_POOL: usize = 100;
