// PDA Seed Prefixes
pub const ALLOVR_MINT_SEED_PREFIX: &'static str = "ALLOVRMINT";
pub const ARTIST_SEED_PREFIX: &'static str = "ALLOVRARTIST";
pub const ARTIST_METADATA_SEED_PREFIX: &'static str = "ALLOVRARTISTMETA";
pub const ARTWORK_SEED_PREFIX: &'static str = "ALLOVRARTWORK";
pub const ARTWORK_METADATA_SEED_PREFIX: &'static str = "ALLOVRARTWORKMETA";
pub const ARTWORK_ESCROW_SEED_PREFIX: &'static str = "ALLOVRARTWORKESCROW";
pub const ALLOVR_AOVR_STAKE_POOL_REGISTRY_PREFIX: &str = "ALLOVRSTAKEPOOLREGISTRY";
pub const ALLOVR_AOVR_STAKE_POOL_PREFIX: &str = "ALLOVRSTAKEPOOL";
pub const ALLOVR_AOVR_STAKE_PREFIX: &str = "ALLOVRSTAKE";

// Other
pub const ALLOVR_AOVR_DECIMAL_PLACES: u8 = 9;
pub const ALLOVR_AOVR_STAKE_NUM_POOLS: usize = 100;
pub const ALLOVR_AOVR_STAKE_NUM_STAKES_IN_POOL: usize = 100;
pub const ALLOVR_AOVR_STAKE_MINIMUM_STAKE: u64 = 10;

pub const INFLATION_INTERVAL_IN_SECONDS: i64 = 604800; // seconds in a week (60 * 60 * 24 * 7);
