export const ALLOVR_AOVR_STAKE_POOL_REGISTRY_PREFIX =
  "ALLOVR_AOVR_STAKE_POOL_REGISTRY";
export const ALLOVR_AOVR_STAKE_POOL_PREFIX = "ALLOVR_AOVR_STAKE_POOL";

export const COST_INITIALISE = 41_000_000;
export const COST_REGISTER_POOL = 6_681_600;

export const ALLOVR_AOVR_STAKE_NUM_POOLS = 100;
export const ALLOVR_AOVR_STAKE_NUM_STAKES_IN_POOL = 100;
