// PDA Seed Prefixes
export const ALLOVR_MINT_SEED_PREFIX = "ALLOVRMINT";
export const ARTIST_SEED_PREFIX = "ALLOVRARTIST";
export const ARTIST_METADATA_SEED_PREFIX = "ALLOVRARTISTMETA";
export const ARTWORK_SEED_PREFIX = "ALLOVRARTWORK";
export const ARTWORK_METADATA_SEED_PREFIX = "ALLOVRARTWORKMETA";
export const ARTWORK_ESCROW_SEED_PREFIXr = "ALLOVRARTWORKESCROW";
export const ALLOVR_AOVR_STAKE_POOL_REGISTRY_PREFIX = "ALLOVRSTAKEPOOLREGISTRY";
export const ALLOVR_AOVR_STAKE_POOL_PREFIX = "ALLOVRSTAKEPOOL";
export const ALLOVR_AOVR_STAKE_PREFIX = "ALLOVRSTAKE";

export const COST_INITIALISE = 41_000_000;
export const COST_REGISTER_POOL = 9_000_000;
export const COST_INIT_AOVR = 9_000_000;

export const ALLOVR_AOVR_DECIMAL_PLACES = 9;
export const ALLOVR_AOVR_STAKE_NUM_POOLS = 100;
export const ALLOVR_AOVR_STAKE_NUM_STAKES_IN_POOL = 100;

export const FOUNDER_1 = "4hwotd4U1obdNgSTdDRmgCciRtpA2RnKgUMXvaNG3UcL";
export const FOUNDER_2 = "2NZQvXp2WH3C7QGaGqZkgdPHQ6NA5HxfFShQk3BZ4hos";
export const FOUNDER_3 = "CHjMvtft2fXfZtG3j7g6XrjwRGLEbL12cQ4JZJkmgCZh";
export const FOUNDER_4 = "9ccPp1Wo3CdnfYsMwQAS4QANbcNSxxBwM2pKHwfj6MnT";
export const FOUNDER_5 = "2c32a1Go7ymoRnhEhbFdeqMhH7NzYmgTnKg81Px3FMmM";
export const FOUNDER_6 = "5nQuotoXmY8eGX8Fvs3Wb4fSHRfSFPHykVZaWsCiQ4i5";
export const FOUNDER_7 = "9yLngfqLsNg89ZGQ4SoM7FrqX2ZChYywPE6paVvrRt5A";
export const FOUNDER_8 = "73f6p31ywabqejWDAUMAo6bd4FGGbhBai2VhJzn3G8jg";
